receivers:
  hostmetrics:
    collection_interval: 15s
    scrapers:
      cpu: {}
      memory: {}
      disk: {}
      filesystem: {}
      network: {}
      paging: {}
      # process: {} # administrative privileges are required to collect process metrics on Windows
      load: {}
      system: {}

  prometheus/windows_exporter:
    config:
      scrape_configs:
        - job_name: windows_exporter
          scrape_interval: 15s
          metrics_path: /metrics
          static_configs:
            - targets: [127.0.0.1:9182]

  prometheus/libre_hardware_monitor:
    config:
      scrape_configs:
        - job_name: libre_hardware_monitor
          scrape_interval: 15s
          static_configs:
            - targets:
                - 127.0.0.1:9190

service:
  pipelines:
    metrics:
      receivers:
        - otlp
        - hostmetrics
        - prometheus/windows_exporter
        - prometheus/libre_hardware_monitor