receivers:
  hostmetrics:
    collection_interval: 15s
    scrapers:
      cpu: {}
      memory: {}
      disk: {}
      filesystem: {}
      network: {}
      paging: {}
      process: {}
      load: {}
      system: {}

service:
  pipelines:
    metrics:
      receivers:
        - otlp
        - hostmetrics